name: mantenimiento_de_bus
description: "App dirigida al mantenimiento de Buses"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  intl: ^0.19.0
  excel: ^2.1.0
  file_picker: ^9.2.1
  url_launcher: ^6.1.12
  permission_handler: ^11.4.0
  shared_preferences: ^2.0.15
  badges: ^3.1.1
  provider: ^6.1.1
  animate_do: ^3.3.4
  lottie: ^3.0.0
  fl_chart: ^0.66.2
  path: ^1.8.3

  firebase_core: ^2.32.0
  firebase_auth: ^4.15.3  # Si usas autenticación
  cloud_firestore: ^4.17.5  # Si usas Firestore

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/