name: mantenimiento_de_bus
description: "App dirigida al mantenimiento de Buses"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  path_provider: ^2.1.2
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  excel: ^2.1.0
  file_picker: ^9.2.1
  url_launcher: ^6.1.12
  permission_handler: ^11.4.0
  shared_preferences: ^2.0.15
  desktop_window: ^0.4.0
  badges: ^3.1.1
  provider: ^6.1.1
  animate_do: ^3.3.4
  lottie: ^3.0.0
  fl_chart: ^0.66.2
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  path: ^1.8.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Italic.ttf
          style: italic
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300